name: Issue Management

on:
  issues:
    types:
      - opened
      - edited

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (required for some actions)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Automatically label issues based on their content
      - name: Auto-label issues
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml